variable "vpc_cidr" {}
variable "vpc_name" {}
variable "subnet_cidr_pub1" {}
variable "subnet_name_pub1" {}
variable "subnet_cidr_pub2" {}
variable "subnet_name_pub2" {}
variable "subnet_cidr_pri1" {}
variable "subnet_name_pri1" {}
variable "subnet_cidr_pri2" {}
variable "subnet_name_pri2" {}
variable "igw_name" {}
variable "RT_name_pub" {}
variable "RT_name_pri" {}
variable "rt_cidr_pub" {}
variable "rt_cidr_pri" {}
variable "EIP_name" {}
variable "Nat_gateway_name" {}
variable "sg_name" {}
variable "inbound_cidr" {}
variable "name_alb" {}
variable "name_tg1" {}
variable "name_tg2" {}
variable "name_tg3" {}
variable "ami_id" {}
variable "instance_type" {}
variable "instance_name" {}
variable "rule_name" {}